apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/nginx
    repoURL: https://github.com/minasaeedbasta/eyouth-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
